# Generated by Django 3.1.1 on 2020-10-01 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(default='AZ', max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('mobile_phone', models.CharField(max_length=200)),
                ('home_phone', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('SSN', models.CharField(blank=True, max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('veteran', models.BooleanField()),
                ('highest_grade_level', models.CharField(choices=[('00-08 Grade', '00-08 Grade'), ('09-12 Non-Graduate', '09-12 Non-Graduate'), ('High school Diploma or GED', 'High school Diploma or GED'), ('Some College/Trade School', 'Some College/Trade School'), ('Associate Degree', 'Associate Degree'), ('4 Year College Degree', '4 Year College Degree'), ('Masters Degree', 'Masters Degree'), ('PhD', 'PhD')], max_length=200)),
                ('disability_deaf', models.BooleanField()),
                ('disability_mobility', models.BooleanField()),
                ('disability_speech', models.BooleanField()),
                ('disability_learning', models.BooleanField()),
                ('disability_visual', models.BooleanField()),
                ('disability_health', models.BooleanField()),
                ('disability_housebound', models.BooleanField()),
                ('disability_other', models.TextField(blank=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('primary_client', models.BooleanField()),
                ('assistance_type', models.CharField(max_length=200)),
                ('housing_type', models.CharField(choices=[('NONE', 'NONE'), ('Rent', 'Rent'), ('Mortgage', 'Mortgage')], max_length=200)),
                ('adults_num', models.IntegerField()),
                ('kids_num', models.IntegerField()),
                ('elderly_num', models.IntegerField()),
                ('income_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('2nd Job', '2nd Job'), ('3rd Job', '3rd Job'), ('TANF', 'TANF'), ('SSI', 'SSI'), ('Pension', 'Pension'), ('Unemployment', 'Unemployment')], max_length=200)),
                ('hh_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('crisis_other', models.TextField()),
                ('crisis_job_related', models.BooleanField()),
                ('crisis_health_problems', models.BooleanField()),
                ('crisis_expenses', models.BooleanField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
