# Generated by Django 3.1.1 on 2020-10-03 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201001_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='SSN',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='adults_num',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='assistance_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='crisis_expenses',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='crisis_health_problems',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='crisis_job_related',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='crisis_other',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_applied',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disability_deaf',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disability_health',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disability_housebound',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disability_learning',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disability_mobility',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disability_other',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disability_speech',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disability_visual',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='elderly_num',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='hh_income',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='highest_grade_level',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='housing_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='income_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='kids_num',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='primary_client',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='race',
        ),
        migrations.CreateModel(
            name='HPAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.CharField(blank=True, max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('highest_grade_level', models.CharField(choices=[('00-08 Grade', '00-08 Grade'), ('09-12 Non-Graduate', '09-12 Non-Graduate'), ('High school Diploma or GED', 'High school Diploma or GED'), ('Some College/Trade School', 'Some College/Trade School'), ('Associate Degree', 'Associate Degree'), ('4 Year College Degree', '4 Year College Degree'), ('Masters Degree', 'Masters Degree'), ('PhD', 'PhD')], max_length=200)),
                ('disability_deaf', models.BooleanField()),
                ('disability_mobility', models.BooleanField()),
                ('disability_speech', models.BooleanField()),
                ('disability_learning', models.BooleanField()),
                ('disability_visual', models.BooleanField()),
                ('disability_health', models.BooleanField()),
                ('disability_housebound', models.BooleanField()),
                ('disability_other', models.TextField(blank=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('primary_client', models.BooleanField()),
                ('assistance_type', models.CharField(max_length=200)),
                ('housing_type', models.CharField(choices=[('NONE', 'NONE'), ('Rent', 'Rent'), ('Mortgage', 'Mortgage')], max_length=200)),
                ('adults_num', models.IntegerField()),
                ('kids_num', models.IntegerField()),
                ('elderly_num', models.IntegerField()),
                ('income_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('2nd Job', '2nd Job'), ('3rd Job', '3rd Job'), ('TANF', 'TANF'), ('SSI', 'SSI'), ('Pension', 'Pension'), ('Unemployment', 'Unemployment')], max_length=200)),
                ('hh_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('crisis_other', models.TextField()),
                ('crisis_job_related', models.BooleanField()),
                ('crisis_health_problems', models.BooleanField()),
                ('crisis_expenses', models.BooleanField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contact')),
            ],
        ),
    ]
