# Generated by Django 3.1.1 on 2020-10-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201002_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpapp',
            name='race',
            field=models.CharField(choices=[('White', 'White'), ('Black or African American', 'Black or African American'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Asian or Asian American', 'Asian or Asian American'), ('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Native Hawaiian or other Pacific Islander', 'Native Hawaiian or other Pacific Islander'), ('American Indian or Alaska Native AND White', 'American Indian or Alaska Native AND White'), ('Asian AND White', 'Asian AND White'), ('Black or African American AND White', 'Black or African American AND White'), ('American Indian or Alaska Native AND Black or African American', 'American Indian or Alaska Native AND Black or African American'), ('Other Multiracial', 'Other Multiracial')], max_length=200),
        ),
    ]
