# Generated by Django 3.1.1 on 2020-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201006_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpapp',
            name='assistance_type',
            field=models.CharField(choices=[('Rent/Mortgage', 'Rent/Mortgage'), ('Rent/Mortgage & Utilities', 'Rent/Mortgage & Utilities')], max_length=200),
        ),
    ]
