# Generated by Django 3.1.1 on 2020-10-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_auto_20201006_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpapp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hpapp',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_provider', models.CharField(choices=[('SRP', 'SRP'), ('APS', 'APS'), ('Southwest Gas', 'Southwest Gas'), ('City of Phoenix', 'City of Phoenix'), ('City of Mesa', 'City of Mesa'), ('City of Peoria', 'City of Peoria'), ('City of Tempe', 'City of Tempe'), ('City of Glendale', 'City of Glendale'), ('City of Chandler', 'City of Chandler'), ('City of Goodyear', 'City of Goodyear'), ('City of Buckeye', 'City of Buckeye'), ('City of Scottsdale', 'City of Scottsdale'), ('Epcor', 'Epcor'), ('Liberty', 'Liberty')], max_length=100)),
                ('utility_type', models.CharField(choices=[('water', 'Water'), ('electric', 'Electric'), ('gas', 'Gas')], max_length=100)),
                ('account_no', models.CharField(max_length=200)),
                ('name_on_acct', models.CharField(max_length=200)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('statement', models.FileField(upload_to=home.models.user_directory_path)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contact')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ll_or_mortage_co', models.CharField(max_length=250)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('mailing_address1', models.CharField(max_length=250)),
                ('mailing_address2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(default='AZ', max_length=10)),
                ('zipcode', models.CharField(max_length=20)),
                ('monthly_payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('current_amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contact')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
