# Generated by Django 3.1.1 on 2020-10-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201013_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilities',
            name='statement',
        ),
    ]
