# Generated by Django 3.1.1 on 2020-10-23 14:46

from django.db import migrations, models
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_utilities_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='statement',
            field=models.FileField(default=django.utils.timezone.now, upload_to=home.models.user_directory_path),
            preserve_default=False,
        ),
    ]
