# Generated by Django 3.1.1 on 2020-10-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20201028_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='payment_due_date',
            field=models.DateField(),
        ),
    ]
